export const CODE_LANGUAGES: [string, string][] = [
  ['plaintext', 'Texto'],
  ['java', 'Java'],
  ['sql', 'SQL'],
  ['xml', 'HTML / XML'],
  ['css', 'CSS'],
  ['javascript', 'JavaScript'],
  ['typescript', 'TypeScript'],
  ['json', 'JSON'],
  ['php', 'PHP'],
  ['python', 'Python'],
  ['bash', 'Bash / Linux'],
  ['powershell', 'PowerShell'],
  ['dos', 'CMD (Windows)'],
  ['yaml', 'YAML'],
  ['markdown', 'Markdown'],
  ['c', 'C'],
  ['cpp', 'C++'],
  ['csharp', 'C#'],
  ['kotlin', 'Kotlin'],
]
